name: Deploy to k8s

on:
  workflow_dispatch:
    inputs:
      host:
        description: "console ip/domain"
        required: true
        type: string
      key:
        description: "console deepfence key"
        required: true
        type: string

jobs:

  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: make cli
        run: |
          make cli
      
      - name: run integration tests
        run: |
          cd $GITHUB_WORKSPACE/tests/integrations && run.sh
